[tools]
starship = "latest"
assh = "latest"
herdr = "latest"
lazygit = "latest"
uv = "latest"
yazi = "latest"
cargo-binstall = "latest"
"cargo:fresh-editor" = "latest"
glow = "latest"
helix = "latest"
